# -*- coding: utf-8 -*-
"""task2.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1n2tbz30wxx2SkX81Bt-OZ8JrqAPSXVPh
"""

# Define factors influencing survival
def will_survive(socio_economic_status, age, gender):
    # Simplified rules for survival prediction
    if socio_economic_status == 'High' and age < 50 and gender == 'Female':
        return "Likely to Survive"
    else:
        return "Not Likely to Survive"

# Input data (you can modify these values)
socio_economic_status = 'High'  # Options: 'Low', 'Medium', 'High'
age = 35
gender = 'Female'  # Options: 'Male', 'Female'

# Predict survival
result = will_survive(socio_economic_status, age, gender)

# Display the prediction
print(f"Based on the provided factors, the person is {result}.")